CircularQueue Q(5);
    Q.enqueue(4);
    Q.enqueue(3);
    Q.enqueue(7);
    Q.enqueue(2);
    Q.Display();
    Q.dequeue();
    Q.dequeue();
    Q.Display();
    Q.dequeue();
    Q.Display();
    Q.enqueue(5);
    Q.enqueue(7);
    Q.enqueue(0);
    Q.Display();